# Generated by Django 4.1.2 on 2022-10-16 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diseases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="symptom",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="symptom",
            name="title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="disease",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DiseaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_symtoms",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало болезни"
                    ),
                ),
                (
                    "recovered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание болезни"
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diseases.disease",
                        verbose_name="Заболевание",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Больной",
                    ),
                ),
                (
                    "symptom",
                    models.ManyToManyField(
                        to="diseases.symptom", verbose_name="Симптом"
                    ),
                ),
            ],
        ),
    ]
