# Generated by Django 4.1.2 on 2022-10-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="echo",
            options={"verbose_name": "Echo", "verbose_name_plural": "Echoes"},
        ),
        migrations.AddField(
            model_name="echo",
            name="ip_address",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="echo",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
