# Generated by Django 4.1.2 on 2023-01-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.ImageField(upload_to="tasks/")),
                ("answer", models.IntegerField()),
            ],
        ),
    ]
